.vscode/tasks.json
tools/scripts/buildModAll.bat
tools/scripts/buildModCLib.bat
tools/scripts/buildModOPT.bat
tools/scripts/createBuildDirectories.bat
tools/scripts/createModDir.bat
tools/scripts/getPBOName.bat

Changed build scripts to use their basepath as reference
Added tasks.json for most common task

Use Basepaths for scripts; add tasks.json for vscode users

---

addons/OPT/macros.hpp

Macros for assertions. Not yet tested

Assertion macros

---

addons/OPT/GPS/fn_IsUnitVisible.sqf
addons/OPT/GPS/fn_addUnitToGPS.sqf

- Versehentlich Farben vertauscht für eigenen Marker mit Gruppenfarbe
- Marker werden nicht mehr für Dummy-AI in Basen angezeigt

Minor GPS Fixes

---

addons/OPT/GPS/fn_addUnitToGPS.sqf

*PLAYERNAME (Verwundet)* oder *PLAYERNAME (Stabilisiert)*

Down-Marker zeigen jetzt Stabilisiert-Zustand an

---

addons/OPT/GPS/fn_clientInit.sqf
addons/OPT/GPS/fn_miniGPS.sqf
addons/OPT/modules.hpp

Erweiterung für MiniGPS Control

GPS Fix MiniGPS

---

addons/OPT/GELDZEIT/fn_serverInit.sqf
addons/OPT/SECTORCONTROL/fn_Punkte.sqf
addons/OPT/SECTORCONTROL/fn_clientInit.sqf

- Sekunden genaue Erfassung der Fahne
- Fix für das Logging des Endpunktestand 
- Fix JIP Flagge ziehen per Taste

Update sektorcontrol punkteerfassung

---

addons/OPT/GELDZEIT/fn_initCBASettings.sqf
addons/OPT/SHOP/fn_clientInit.sqf
addons/OPT/SHOP/fn_config.sqf
addons/OPT/SHOP/fn_create.sqf
addons/OPT/SHOP/fn_serverInit.sqf

Shop änderung Kampagne 2021

---

addons/OPT/GELDZEIT/fn_serverInit.sqf
addons/OPT/GELDZEIT/fn_updatebudget.sqf
addons/OPT/LOGGING/fn_writelog.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/SHOP/fn_create.sqf
addons/OPT/SHOP/fn_einlesenInKonfigDialog.sqf
addons/OPT/SHOP/fn_einlesenInVerkaufDialog.sqf
addons/OPT/SHOP/fn_handledeadvehicle.sqf
addons/OPT/SHOP/fn_writekill.sqf
addons/OPT/WEATHERTIME/fn_initCBASettings.sqf

Anpassungen fürs Logging

---

addons/OPT/RULES/fn_setup_classnames.sqf
addons/OPT/SECTORCONTROL/fn_addflagmenu.sqf
addons/OPT/SECTORCONTROL/fn_setupflagpositions.sqf

Slottsperren angepasst 
Flaggen eingetragen

Bugfix 20 12 20

---

addons/OPT/CARGO/fn_setupcargospaceandsize.sqf
addons/OPT/GPS/fn_gps.sqf
addons/OPT/GPS/fn_gps_Unconscious.sqf
addons/OPT/RULES/fn_clientInit.sqf
addons/OPT/SECTORCONTROL/fn_clientinitplayereh.sqf
addons/OPT/SHOP/fn_config.sqf

Restarbeiten kampagne 2021

---

addons/OPT/SECTORCONTROL/fn_clientInit.sqf

Bugfix Minensperrzone

---

addons/OPT/CfgCLibLocalisation.hpp
addons/OPT/GELDZEIT/fn_earplugs.sqf

Add new setting for earplugs. Now players can switch between 25%/50%/0%

New Earplugs Setting

---

addons/OPT/GELDZEIT/fn_serverInit.sqf
addons/OPT/GELDZEIT/fn_updatebudget.sqf
addons/OPT/GELDZEIT/fn_writeplayerlist.sqf
addons/OPT/SHOP/fn_config.sqf

Kleine Erweiterungen fürs Logging:
- Fraktionsübersicht
- Fahrzeug-Kategorien schon beim Kaufen loggen

Kleine Erweiterungen fürs Logging

---

addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_dialog.sqf
addons/OPT/SECTORCONTROL/fn_writeflagcaptured.sqf

- flaggen-log bedingungen vereinfacht und verschärft
- Für alle zum Schluss anwesenden (25 m) Kameraden einen Revive-Punkt loggen
- Respawns loggen

small logging fixes

---

addons/OPT/FIELDREPAIR/fn_clientcbaclassevents.sqf
addons/OPT/FIELDREPAIR/fn_heavyrepair.sqf
addons/OPT/FIELDREPAIR/fn_initcbaclassevents.sqf
addons/OPT/GELDZEIT/fn_ende.sqf
addons/OPT/GELDZEIT/fn_serverInit.sqf
addons/OPT/REVIVE/fn_checkdragging.sqf
addons/OPT/REVIVE/fn_checkplaymove.sqf
addons/OPT/REVIVE/fn_clientInit.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_drag.sqf
addons/OPT/REVIVE/fn_handleaction.sqf
addons/OPT/REVIVE/fn_initCBASettings.sqf
addons/OPT/REVIVE/fn_initcbaclassevents.sqf
addons/OPT/REVIVE/fn_release.sqf
addons/OPT/RULES/fn_setup_classnames.sqf
addons/OPT/SHOP/fn_config.sqf
addons/OPT/SHOP/fn_deletevehicle.sqf
addons/OPT/SHOP/fn_handledeadvehicle.sqf
addons/OPT/modules.hpp

Ergängungen vom Konzeptteam und Bugfix

---

addons/OPT/REVIVE/fn_clientInitEH.sqf

bitte von diesem stand weiterarbeiten,
da in REVIVE\fn_clientInitEH.sqf noch eine einzelne Zeile von mir dazukam, die in Lords alter PBO nicht drin war.
Die Zeile darf nicht unter den Tisch fallen :)

geaendertes file vom hotfix der testschlacht3

---

addons/OPT/FIELDREPAIR/fn_clientInit.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_initCBASettings.sqf
addons/OPT/REVIVE/fn_initcbaclassevents.sqf
addons/OPT/RULES/fn_setup_classnames.sqf
addons/OPT/SHOP/fn_getvehicleinfo.sqf

Bugfix Techschlacht3

---

addons/OPT/REVIVE/fn_checkdragging.sqf
addons/OPT/REVIVE/fn_clientInit.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_drag.sqf

Bugfix zum ziehen von bewusstlosen in Revivesystem

Bugfix Drag Revive

---

addons/OPT/CARGO/fn_setupcargospaceandsize.sqf
addons/OPT/RULES/fn_clientInit.sqf
addons/OPT/RULES/fn_setup_classnames.sqf
addons/OPT/RULES/fn_weaponcheck.sqf
addons/OPT/SECTORCONTROL/fn_clientInit.sqf
addons/OPT/SECTORCONTROL/fn_setupflagpositions.sqf
addons/OPT/SHOP/fn_config.sqf
addons/OPT/SHOP/fn_serverInit.sqf

Aenderung prologschlacht

---

addons/OPT/RULES/fn_setup_classnames.sqf
addons/OPT/RULES/fn_weaponcheck.sqf

Bugfix Meldung Waffencheck

---

addons/OPT/SECTORCONTROL/fn_setupflagpositions.sqf

https://opt4.net/forum/index.php?thread/3686-entwickler-sprechblase/&postID=98987#post98987

fahne 14_2 verschoben

---

addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/macros.hpp

Mein versuch den respawn Bug zu beheben.

fix instant respawn

---

addons/OPT/GELDZEIT/fn_clientInit.sqf
addons/OPT/GELDZEIT/fn_init.sqf
addons/OPT/GPS/fn_gps.sqf
addons/OPT/GPS/fn_gps_Unconscious.sqf
addons/OPT/REVIVE/fn_checkplaymove.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_drag.sqf
addons/OPT/SHOP/fn_einlesenInShopDialog.sqf
addons/OPT/SHOP/fn_handledeadvehicle.sqf

Restarbeiten 

---

addons/OPT/SHOP/fn_deletevehicle.sqf

Fix Shop Pad Räumen

---

addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/macros.hpp

* Removing SecureAction from incapacitated players
the function only get added to the client, but to the incapacitated unit (client sided), was kinda tricky to figure that out.
Thanks to TeTeT for this working piece.

Fix handcuffing

---

addons/OPT/FIELDREPAIR/fn_vehicleDamagedLight.sqf

Fange hiermit ein zwar erstelltes aber Leeres Array ab.
Keine Ahnung ob das die schönste Lösung ist kann ja wer schlaues draufschauen.

fix zero div in fn_vehicleDamageLight.sqf

---

addons/OPT/REVIVE/fn_handleaction.sqf
addons/OPT/SHOP/fn_handledeadvehicle.sqf
addons/OPT/SHOP/fn_writetransportdistance.sqf
addons/OPT/modules.hpp

Fix feedback optimierung

---

addons/OPT/SECTORCONTROL/fn_teleport.sqf
addons/OPT/SHOP/fn_clientInitcbaclassevents.sqf
addons/OPT/macros.hpp

- hotfix für mehrfaches flugdistanz-logging
- fix für teleport auf non-terrain positionen

hotfix for flightdistance, fix for teleport

---

addons/OPT/GELDZEIT/fn_beam.sqf
addons/OPT/GPS/fn_gps.sqf
addons/OPT/GPS/fn_gps_Unconscious.sqf
addons/OPT/REVIVE/fn_clientInitEH.sqf
addons/OPT/REVIVE/fn_dialog.sqf
addons/OPT/REVIVE/macros.hpp
addons/OPT/SHOP/fn_einlesenInShopDialog.sqf

Bugfix und Verbesserung Schlacht 5

---

.gitignore
hemtt.toml

- Vorbereitung für das HEMTT Build-System

Preparation for HEMTT

---

addons/OPT/SHOP/macros.hpp
addons/main/SHOP/fn_Init.sqf
addons/main/SHOP/fn_clientInitcbaclassevents.sqf
addons/main/script_version.hpp

Fix Bug JIP ausraemen

---

addons/main/GPS/fn_gps.sqf
addons/main/script_version.hpp

GPS Update

---

addons/main/GPS/fn_clientInit.sqf
addons/main/GPS/fn_createplayermarker.sqf
addons/main/GPS/fn_createunitmarker.sqf
addons/main/GPS/fn_createunitmarker_Unconscious.sqf
addons/main/GPS/fn_gps.sqf
addons/main/GPS/fn_gps_Unconscious.sqf
addons/main/GPS/fn_selectunits.sqf
addons/main/GPS/macros.hpp
addons/main/modules.hpp
addons/main/script_version.hpp

Altes GPS mit einigen Verbesserungen

Rollback des GPS

---

addons/main/GPS/fn_clientInit.sqf
addons/main/GPS/fn_createunitmarker.sqf
addons/main/GPS/fn_gps.sqf

GPS Marker Symbol geändert

---

addons/main/CfgCLibLocalisation.hpp
addons/main/GELDZEIT/fn_clientInitcbaclassevents.sqf
addons/main/GELDZEIT/fn_haftladungen.sqf
addons/main/modules.hpp
addons/main/script_version.hpp

Nachrüsten der Funktion zum Anbringen von Sprendladungen an Fahrzeugen.

Haftladungen 

---

addons/main/GELDZEIT/fn_haftladungen.sqf
addons/main/script_version.hpp

Haftladungen

---

addons/main/GELDZEIT/fn_clientInitcbaclassevents.sqf
addons/main/SECTORCONTROL/fn_clientinitplayereh.sqf
addons/main/SECTORCONTROL/fn_drawsectormarkers.sqf
addons/main/script_version.hpp

`worldName` gibt den Kartenname auf Linux Servern kleingeschrieben zurück.

case-insensitivity for linux server

---

addons/main/GELDZEIT/fn_updatebudget.sqf
addons/main/SHOP/fn_unflip.sqf
addons/main/SHOP/fn_writekill.sqf
addons/main/script_version.hpp

Kategorien Logging für Ausrüstung und statische Waffen.

completed categories

---

addons/main/RULES/fn_setup_classnames.sqf
addons/main/SHOP/fn_config.sqf
addons/main/SHOP/fn_initCBASettings.sqf
addons/main/SHOP/fn_serverInit.sqf

- Add Weapon Classnames to weaponcheck 
- Add Unitclassnames to Weaponcheck
- Add statics to shopconfig
- Cleanup for unused classes and weapons
- Add Helicopters to pilot_vecs
- Add armor to crew_vecs
- Add Hardcaps for vehicles

Loadout - Statics, Weapons and Units

---

addons/main/SHOP/fn_config.sqf

Prepare for the next campaign, replace vanilla/contact vehicles with CUP vehicles.

Update shop with CUP vehicles

---

addons/main/GELDZEIT/fn_initCBASettings.sqf
addons/main/GELDZEIT/fn_spritverbrauch.sqf
addons/main/SHOP/fn_clientInitcbaclassevents.sqf
addons/main/modules.hpp
addons/main/script_version.hpp

Erhöhter Treibstoffverbrauch bei Lufteinheiten

---

addons/main/GELDZEIT/fn_serverInit.sqf
addons/main/RULES/fn_clientInit.sqf
addons/main/RULES/fn_setup_classnames.sqf
addons/main/RULES/fn_weaponcheck.sqf
addons/main/SECTORCONTROL/fn_clientInit.sqf
addons/main/SHOP/fn_checkpad.sqf
addons/main/SHOP/fn_clientInit.sqf
addons/main/SHOP/fn_config.sqf
addons/main/SHOP/fn_create.sqf
addons/main/SHOP/fn_einlesenInKonfigDialog.sqf
addons/main/SHOP/fn_einlesenInShopDialog.sqf
addons/main/modules.hpp
addons/main/script_version.hpp

Merge-Fixes, Jetpiloten, Cheat-Reporting, Shop-Kollisionserkennung, Zivilflughäfen

---

addons/main/SHOP/fn_serverInit.sqf

Fix NATO Supply Hardcap

---

addons/main/SHOP/fn_create.sqf
addons/main/SHOP/fn_handledeadvehicle.sqf
addons/main/SHOP/fn_order.sqf
addons/main/SHOP/fn_serverInit.sqf
addons/main/script_version.hpp

Wenn ein Kauf innerhalb der ersten 5 Sekunden explodiert, erfolgt eine Gutschrift über den vollen Kaufpreis.

Gutschrift für explodierte Käufe

---

addons/main/GELDZEIT/fn_beam.sqf
addons/main/RULES/fn_setup_classnames.sqf
addons/main/SECTORCONTROL/fn_setupsectors.sqf

Erst kurz vor der Schlacht mergen

Fahne und Beampositionen für TechCheck Schlacht 1

---

addons/main/GELDZEIT/fn_beam.sqf
addons/main/SECTORCONTROL/fn_setupsectors.sqf
addons/main/script_version.hpp

revert techcheck

---

addons/main/CfgCLibLocalisation.hpp
addons/main/SHOP/fn_config.sqf
addons/main/SHOP/fn_einlesenInShopDialog.sqf
addons/main/SHOP/fn_order.sqf
addons/main/script_version.hpp

Dispo, Sortierung, Räumung

---

addons/main/BEAM/fn_beam2.sqf
addons/main/BEAM/fn_beammapmove.sqf
addons/main/BEAM/fn_clientInit.sqf
addons/main/BEAM/fn_onloaddialog.sqf
addons/main/SECTORCONTROL/fn_setupsectors.sqf
addons/main/modules.hpp
addons/main/script_version.hpp

- aufruf testweise derzeit nur über den alten hotkey
- teleport erfolgt testweise derzeit nur mit simplem setpos

WIP: new old beam system

---

addons/main/SHOP/fn_clientInit.sqf
addons/main/SHOP/fn_einlesenInShopDialog.sqf
addons/main/script_version.hpp

Verbesserung Shop aufruf

---

addons/main/SHOP/fn_config.sqf

- Changed Prices for the Vehicles 
- Add new uavs to pricelist
- Add neophron to pricelist
- Add landing craft to pricelist

Vehicle Pricelist Chernarus '22

---

addons/main/CfgCLibLocalisation.hpp
addons/main/INTRO/fn_clientInit.sqf
addons/main/INTRO/fn_dialog.sqf
addons/main/INTRO/fn_initCBASettings.sqf
addons/main/RULES/fn_clientInit.sqf
addons/main/RULES/fn_setup_classnames.sqf
addons/main/RULES/fn_uav.sqf
addons/main/script_version.hpp

Intro nachbearbeitet

---

addons/main/GELDZEIT/fn_spritverbrauch.sqf
addons/main/SHOP/fn_clientInit.sqf
addons/main/SHOP/fn_clientInitcbaclassevents.sqf
addons/main/script_version.hpp

Fix KI Drohne Funktion 

---

addons/main/SHOP/fn_config.sqf

KHS aus kleinen Kontingent entfernen

---

addons/main/REVIVE/fn_clientInit.sqf
addons/main/REVIVE/fn_clientInitEH.sqf
addons/main/REVIVE/fn_dialog.sqf
addons/main/REVIVE/fn_initCBASettings.sqf

Event 2024 Anpassungen 2
