OperationPandoraTrigger/OPT-Server-Mod

- addons/OPT/macros.hpp
Usage: `ERROR_LOG("Your error message here")`
> Macro for error-reporting

- addons/OPT/GPS/fn_IsUnitLeader.sqf
- addons/OPT/GPS/fn_addUnitToGPS.sqf
- Down-Marker ändert Farbe auf Orange, wenn Spieler stabilisiert wurde
- Gruppenführer-Status wird jetzt hart in Abhängigkeit vom Unittype erkannt (nur Offizier, Gruppenführer, Pilot)
> Downmarkerfarbe + Grouplead-Check Update

- addons/OPT/SECTORCONTROL/fn_initCBASettings.sqf
"Angegriffene XX Sektor" was a very irritating label. Replaced it for a simpler to understand "Verteidigungssektor" label.
> fix irritating label for CBA values

- addons/OPT/SECTORCONTROL/fn_Punkte.sqf
Durch das gefixte sekündliche Punktezählen gab es im Log nun sekündlichen Missionstate-Spam.
Durch die nun extrem hässliche Platzierung des Befehls an 9 verschiedenen Stellen im Kackcode sollte nun nur noch bei Punkteveränderung oder 1x pro Minute geloggt werden.
> log missionstate only on change or minutely

- addons/OPT/GELDZEIT/fn_serverInit.sqf
- addons/OPT/SECTORCONTROL/fn_deletesectormarkers.sqf
- addons/OPT/SECTORCONTROL/fn_drawline.sqf
- addons/OPT/SECTORCONTROL/fn_drawsectormarkers.sqf
- addons/OPT/SECTORCONTROL/fn_serverInit.sqf
- addons/OPT/SECTORCONTROL/fn_setupflagpositions.sqf
- addons/OPT/macros.hpp
- addons/OPT/modules.hpp
> Sektorenmarker (Grenzlinien) auf der Karte

- addons/OPT/GELDZEIT/fn_updateplayerlist.sqf
Die Playerlist (die bei Missionsende im Log ausgegeben wird) wird bei jedem Umslotten nun dynamisch aktualisiert, damit die zuletzt gespielte Fraktion des Spielers für die weitere Statistikauswertung herangezogen werden kann.
> dynamic playerlist

- addons/OPT/REVIVE/fn_clientInitEH.sqf
Weitere Absicherung die verhindern soll das der Spieler einen Schaden höher als 1.0 bekommt und so der Autorespwan eingeleitet wird. Der schaden wir gelöscht und auf den CBA Wert zurück gestellt.
> Erweiterung Sicherung für Autorepawn bei Revive

- addons/OPT/SHOP/fn_create.sqf
- addons/OPT/macros.hpp
Reihenfolge getauscht.
Anstatt erst zu Platzieren und dann Verschieben wird jetzt direkt an der richtigen Stelle gespawnt.
> fixed vehicle placement

- addons/OPT/GPS/fn_clientInit.sqf
- addons/OPT/SHOP/fn_clientInitcbaclassevents.sqf
- addons/OPT/SHOP/fn_writetransportdistance.sqf
- Mini-GPS auf Karte standardmäßig deaktiviert (ist eh nur im Weg - Kann vom User aber wieder aktiviert werden)
- Minimaldistanz für Transportlog von 1000 auf 50 Meter reduziert
> Disable GPS on map and reduced minimaldistance

- .gitmodules
`dependencies/CLib` folgt jetzt dem (geforkten) main-branch.
> Make submodule tracking the main branch

- addons/OPT/GELDZEIT/fn_frezztime.sqf
- addons/OPT/GELDZEIT/fn_serverInit.sqf
- addons/OPT/HUD/fn_updatehud.sqf
- addons/OPT/SECTORCONTROL/fn_Punkte.sqf
- addons/OPT/SECTORCONTROL/fn_addflagmenu.sqf
- addons/OPT/SECTORCONTROL/fn_captureflagcondition.sqf
- addons/OPT/SECTORCONTROL/fn_serverInit.sqf
- addons/OPT/SECTORCONTROL/fn_setupflag.sqf
- addons/OPT/SHOP/fn_handledeadvehicle.sqf
- addons/OPT/macros.hpp
- Der nächste Spielabschnitt wird jetzt nicht mehr per `CLib_fnc_wait` mit einer festen Zeit abgewartet, sondern eine Statemachine in einem PFH entscheidet anhand des Timestamps wann der nächste Spielabschnitt startet.
- Wrack-Räum-Script repariert
- Im HUD angezeigter Countdown zeigt nun nicht mehr "60" Sekunden hinten an
> Fix für Missions-Ende

- addons/main/RULES/fn_clientInit.sqf
- addons/main/script_version.hpp
Die Erkennung ob sich ein Feindspieler im Basis-Kreis befindet war vorher basierend auf der Beampad-Position, was eine leichte Differenz zum auf der Karte angezeigten Kreismarker ergab.
> Feindspieler Basis-Eintritt auf Kreismarker geändert

- addons/main/REVIVE/fn_clientInit.sqf
- addons/main/REVIVE/fn_clientInitEH.sqf
Setzt beim Respawnen die TFAR-Verschlüsselung zurück. Könnte helfen falls zwischendurch komische Dinge passiert sind.
> Reset TFAR encryption on respawn

- addons/main/GPS/fn_gps.sqf
- addons/main/script_version.hpp
Die Farbänderung in der einmaligen Marker-Initialisierung wurde versehentlich zum Server gebroadcasted. Zum Glück ist dabei nichts kaputt gegangen 😅
Danke an @DragonGER für die Meldung!
> Fix GPS colorchange to local

- addons/main/CfgCLibLocalisation.hpp
- addons/main/SECTORCONTROL/fn_teleport.sqf
- Warnung bei Bäumen im Zielgebiet (90% Detektionswahrscheinlichkeit, 10% fallen leider durchs Raster)
- Teleport auf Brücken klappt nun
- Helikopterflughöhe wird nicht mehr auf Null gesetzt wenn Teleport über Wasser
- Fahrzeuge werden korrekt an die Bodenbeschaffenheit ausgerichtet
> Teleport Verbesserungen

- addons/main/SECTORCONTROL/fn_setupflagpoles.sqf
Beseitigt das Problem mit der Flagge unter Wasser (unter der Brücke) in Schlacht 6.
> HotFix für korrekte Flaggenplatzierung auf Brücken

- addons/main/GPS/fn_clientInit.sqf
Nach der Planungsphase auf der Karte, beim Durchstarten in die Waffenruhe, wird die Checkbox zum Timestampen der eigenen Marker bei jedem Spieler gesetzt. Kann im laufe der Schlacht von jedem Spieler auch wieder zurückgesetzt werden.
> Timestamping von Markern aktivieren als default

- addons/main/CfgCLibLocalisation.hpp
- addons/main/GELDZEIT/fn_beam.sqf
- addons/main/GELDZEIT/fn_clientInitcbaclassevents.sqf
- addons/main/GELDZEIT/fn_serverInit.sqf
- addons/main/REVIVE/fn_clientInitEH.sqf
- addons/main/RULES/fn_clientInit.sqf
- addons/main/RULES/fn_setup_classnames.sqf
- addons/main/SECTORCONTROL/fn_clientInit.sqf
- addons/main/SECTORCONTROL/fn_clientinitplayereh.sqf
- addons/main/SECTORCONTROL/fn_setupsectors.sqf
- addons/main/SECTORCONTROL/fn_teleport.sqf
- addons/main/SHOP/fn_clientInit.sqf
- addons/main/SHOP/fn_create.sqf
- addons/main/SHOP/fn_einlesenInShopDialog.sqf
- addons/main/SHOP/fn_einlesenInVerkaufDialog.sqf
- addons/main/script_version.hpp
> Diverse Dinge

- addons/main/SECTORCONTROL/fn_initCBASettings.sqf
Die CBA-Einstellungen der Verteidigungssektoren zeigen keinen Hinweis mehr an, der fälschlicherweise besagt das der Server dafür restarted werden müsste.
> sectorsNeedsNoRestart

- addons/main/SECTORCONTROL/fn_serverInit.sqf
- addons/main/SHOP/fn_config.sqf
- addons/main/script_version.hpp
> Spieleranzahl auf der Karte anzeigen, Cessna deaktiviert
